# Generated by Django 2.1.3 on 2018-11-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='weight',
            field=models.FloatField(),
        ),
    ]
