# Generated by Django 2.1.3 on 2018-11-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0002_auto_20181126_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cataegory_tips',
            name='tips',
        ),
        migrations.AddField(
            model_name='cataegory_tips',
            name='dintips',
            field=models.ManyToManyField(related_name='din', to='fit.Tips'),
        ),
        migrations.AddField(
            model_name='cataegory_tips',
            name='exercices',
            field=models.ManyToManyField(related_name='exe', to='fit.Tips'),
        ),
        migrations.AddField(
            model_name='cataegory_tips',
            name='mortips',
            field=models.ManyToManyField(related_name='mor', to='fit.Tips'),
        ),
        migrations.AddField(
            model_name='cataegory_tips',
            name='noontips',
            field=models.ManyToManyField(related_name='noon', to='fit.Tips'),
        ),
    ]
